// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXbE5zRaKV-GtIuStj3tLeOxX3gwUEOPI',
    appId: '1:844474068672:web:2a60d9fd8b0547efb60725',
    messagingSenderId: '844474068672',
    projectId: 'odyssey-f0821',
    authDomain: 'odyssey-f0821.firebaseapp.com',
    storageBucket: 'odyssey-f0821.firebasestorage.app',
    measurementId: 'G-P2E1JL8VJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4wZoEAMhBBcz224ZNaRwMypiGRa-I2-I',
    appId: '1:844474068672:android:3f664dae0be6d300b60725',
    messagingSenderId: '844474068672',
    projectId: 'odyssey-f0821',
    storageBucket: 'odyssey-f0821.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTzwdPJ1qxVUfxkTXKWJnJ0SgyrCi6yUg',
    appId: '1:844474068672:ios:f78944444f30163cb60725',
    messagingSenderId: '844474068672',
    projectId: 'odyssey-f0821',
    storageBucket: 'odyssey-f0821.firebasestorage.app',
    iosBundleId: 'com.example.odyssey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTzwdPJ1qxVUfxkTXKWJnJ0SgyrCi6yUg',
    appId: '1:844474068672:ios:f78944444f30163cb60725',
    messagingSenderId: '844474068672',
    projectId: 'odyssey-f0821',
    storageBucket: 'odyssey-f0821.firebasestorage.app',
    iosBundleId: 'com.example.odyssey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXbE5zRaKV-GtIuStj3tLeOxX3gwUEOPI',
    appId: '1:844474068672:web:b5f73f1fa87e56fdb60725',
    messagingSenderId: '844474068672',
    projectId: 'odyssey-f0821',
    authDomain: 'odyssey-f0821.firebaseapp.com',
    storageBucket: 'odyssey-f0821.firebasestorage.app',
    measurementId: 'G-QZP7X1D2JE',
  );
}
